Repository ether/etherpad-next, pull requests merged in 2024-03, with the labels that each got.

#55 build(lint): better linting
  .eslintrc.json
  app/socket-demo/page.tsx
  components/Logo/Platform/platform-logos.stories.tsx
  lib/settings.ts
  package-lock.json
  package.json
  turbo.json
Labels: Fast-track ⚡️

#58 fix: storybook deploy
  .github/workflows/deploy-storybook.yml
Labels: github_actions

#67 feat(docker): introduce
  .dockerignore
  .env.example
  Dockerfile
  docker-compose.yml
  docs/Techincal.md
  docs/User.md
  package-lock.json
  package.json
  prisma/schema.prisma
Labels: infrastructure
